<Project>
  <PropertyGroup>
    <ArtifactsPath>$(MSBuildThisFileDirectory)build\</ArtifactsPath>
    <BaseOutputPath>$(ArtifactsPath)bin\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(ArtifactsPath)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>